
services:
  flask_app:
    container_name: fetal_classifier_app
    image: atharvv29k/flask_live_app:1.0.0
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
      - FLASK_ENV=development
    depends_on:
      - flask_db
  
  flask_db:
    container_name: fetal_classifier_db
    image: postgres:13
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata: {}